[package]
name = "pi"
version = "0.1.0"
authors = ["Tatsuya Kawano <tatsuya@hibaridb.org>"]

[lib]
name = "pi_nif"
crate-type = ["dylib"]

[dependencies]
ruster_unsafe = { git = "https://github.com/tatsuya6502/ruster_unsafe/", rev = "nif-2.9-unmerged" }
libc = ">=0.2.4"
